export interface BonCaisse {
    numBon: string; // ID du bon
    codSoc?: string; // Code Société (optionnel)
    codRep?: string; // Code Répartition (optionnel)
    libelleBon?: string; // Libellé Bon (optionnel)
    dept?: string; // Département (optionnel)
    mntBon?: number; // Montant Bon (optionnel)
    datBon?: string; // Date Bon en format ISO 8601 (optionnel)
    codTier?: string; // Code Tiers (optionnel)
    codGestion?: string; // Code Gestion (optionnel)
    nQuittance?: number; // Numéro Quittance (optionnel)
    datQuittance?: string; // Date Quittance en format ISO 8601 (optionnel)
    numBord?: number; // Numéro Bordereau (optionnel)
    mntQuittance?: number; // Montant Quittance (optionnel)
    etat?: string; // État (optionnel)
    codProjet?: string; // Code Projet (optionnel)
    codLog?: string; // Code Logement (optionnel)
    userIp?: string; // IP de l'utilisateur (optionnel)
    userMac?: string; // MAC de l'utilisateur (optionnel)
    userUp?: string; // Utilisateur de mise à jour (optionnel)
  }

  export interface DetBonCaisse {
    numBon: string; // Numéro Bon (ID composite)
    lig: number; // Numéro de Ligne (ID composite)
    codSoc?: string; // Code Société (optionnel)
    codRep?: string; // Code Répartition (optionnel)
    codRub?: string; // Code Rubrique (optionnel)
    codProjet?: string; // Code Projet (optionnel)
    nbrMens?: number; // Nombre de Mensualités (optionnel)
    echDeb?: string; // Échéance Début en format ISO 8601 (optionnel)
    echFin?: string; // Échéance Fin en format ISO 8601 (optionnel)
    mnt?: number; // Montant (optionnel)
    userIp?: string; // IP de l'utilisateur (optionnel)
    userMac?: string; // MAC de l'utilisateur (optionnel)
    userUp?: string; // Utilisateur de mise à jour (optionnel)
}
export interface DelarImpots {
    irpp?: number; // IRPP (optionnel)
    revNet?: number; // Revenu Net (optionnel)
    redevance?: number; // Redevance (optionnel)
    parExp?: number; // Par Expérience (optionnel)
    baseExp?: number; // Base Expérience (optionnel)
    baseRedv?: number; // Base Redevance (optionnel)
    codSoc?: string; // Code Société (optionnel)
    annee?: number; // Année (optionnel)
    matricule?: string; // Matricule (optionnel)
    nomPrenom?: string; // Nom et Prénom (optionnel)
    cin?: string; // CIN (optionnel)
    sitFam?: string; // Situation Familiale (optionnel)
    emploi?: string; // Emploi (optionnel)
    enfantAChrg?: number; // Enfants à Charge (optionnel)
    adresse?: string; // Adresse (optionnel)
    dateDeb?: string; // Date Début en format ISO 8601 (optionnel)
    dateFin?: string; // Date Fin en format ISO 8601 (optionnel)
    revImpsable?: number; // Revenu Imposable (optionnel)
    revAvNature?: number; // Revenu Avant Nature (optionnel)
    revBrutImposable?: number; // Revenu Brut Imposable (optionnel)
    revReinvesti?: number; // Revenu Réinvesti (optionnel)
}
export interface DetTransfertGrh {
    codSoc?: string; // Code Société (optionnel)
    codRep?: string; // Code Répartition (optionnel)
    numTransf?: string; // Numéro Transfert (optionnel)
    datTransf?: string; // Date Transfert en format ISO 8601 (optionnel)
    numLig?: number; // Numéro Ligne (optionnel)
    datPiece?: string; // Date Pièce en format ISO 8601 (optionnel)
    codTyp?: string; // Code Type (optionnel)
    libPiece?: string; // Libellé Pièce (optionnel)
    mntPiece?: number; // Montant Pièce (optionnel)
    sens?: string; // Sens (optionnel)
    codDep?: string; // Code Département (optionnel)
    codBnp?: string; // Code Banque (optionnel)
    codRub?: string; // Code Rubrique (optionnel)
    typSal?: string; // Type Salaire (optionnel)
    codTier?: string; // Code Tiers (optionnel)
    matPers?: string; // Matricule Personnel (optionnel)
    trsf?: string; // Transfert (optionnel)
}
export interface TransfertGrh {
    codSoc?: string; // Code Société (optionnel)
    codRep?: string; // Code Répartition (optionnel)
    numTransf?: string; // Numéro Transfert (optionnel)
    datTransf?: string; // Date Transfert en format ISO 8601 (optionnel)
    transf?: string; // Transfert (optionnel)
    seqEcrt?: number; // Séquence Écriture (optionnel)
    datCompta?: string; // Date Comptabilité en format ISO 8601 (optionnel)
    userCompta?: number; // Utilisateur Comptabilité (optionnel)
}
export interface InscriptionDet {
    inscriptionDetId?: number; // ID de l'inscription (optionnel)
    inscriptionDetConcours?: string; // Concours (optionnel)
    inscriptionDetCin?: number; // CIN (optionnel)
    inscriptionDetNom?: string; // Nom (optionnel)
    inscriptionDetPrenom?: string; // Prénom (optionnel)
    inscriptionDetNaissDate?: string; // Date de Naissance en format ISO 8601 (optionnel)
    inscriptionDetNaissVille?: string; // Ville de Naissance (optionnel)
    inscriptionDetNaissGouv?: string; // Gouvernorat de Naissance (optionnel)
    inscriptionDetEmail?: string; // Email (optionnel)
    inscriptionDetTelFixe?: string; // Téléphone Fixe (optionnel)
    inscriptionDetTelMobile?: string; // Téléphone Mobile (optionnel)
    inscriptionDetAdresse?: string; // Adresse (optionnel)
    inscriptionDetGouvernorat?: string; // Gouvernorat (optionnel)
    inscriptionDetFormationDesc?: string; // Description Formation (optionnel)
    inscriptionDetDiplome?: string; // Diplôme (optionnel)
    inscriptionDetUniversite?: string; // Université (optionnel)
    inscriptionDetSpecialite?: string; // Spécialité (optionnel)
    inscriptionDetDiplomeDate?: string; // Date du Diplôme en format ISO 8601 (optionnel)
    inscriptionDetExperience?: string; // Expérience (optionnel)
    inscriptionDetMotivation?: string; // Motivation (optionnel)
    inscriptionDetDateInscri?: string; // Date d'inscription en format ISO 8601 (optionnel)
    concoursId?: number; // ID du Concours (optionnel)
    inscriptionDetSexe?: string; // Sexe (optionnel)
    inscriptionDetScore?: number; // Score (optionnel)
    inscriptionDetMoyDip?: number; // Moyenne Diplôme (optionnel)
    inscriptionDetMoyBac?: number; // Moyenne Baccalauréat (optionnel)
    inscriptionDetMoyBtp?: number; // Moyenne BTP (optionnel)
    inscriptionDetChomage?: string; // Chômage (optionnel)
    inscriptionDetMoyAnnee?: number; // Moyenne Année (optionnel)
}


export interface OrdreVersement {
    id?: number; // ID (optionnel)
    dateDebut?: string; // Date Début en format ISO 8601 (optionnel)
    dateFin?: string; // Date Fin en format ISO 8601 (optionnel)
    montantEncaisse?: number; // Montant Encaissé (optionnel)
    codeOrdreVersement?: string; // Code Ordre de Versement (optionnel)
}


export interface PsTxn {
    id?: number; // ID (optionnel)
    parentId?: number; // ID Parent (optionnel)
    collId?: number; // ID Collection (optionnel)
    content?: Blob; // Contenu (optionnel)
    creationDate?: string; // Date de Création en format ISO 8601 (optionnel)
}


export interface Client {
    codSoc?: string; // Code Société (optionnel)
    codRep?: string; // Code Répartition (optionnel)
    ancTier?: string; // Ancien Tiers (optionnel)
    typTier?: string; // Type Tiers (optionnel)
    nomTier?: string; // Nom du Tiers (optionnel)
    telTier?: string; // Téléphone du Tiers (optionnel)
    faxTier?: string; // Fax du Tiers (optionnel)
    adrTier?: string; // Adresse du Tiers (optionnel)
    ville?: string; // Ville (optionnel)
    typPiece?: string; // Type de Pièce (optionnel)
    matFisc?: string; // Matricule Fiscal (optionnel)
    resident?: string; // Résident (optionnel)
    natTier?: string; // Nationalité du Tiers (optionnel)
    acqlocCliBe?: string; // Acquisition ou Location Client BE (optionnel)
    codCli?: string; // Code Client (optionnel)
    matCli?: number; // Matricule Client (optionnel)
    acqlocCli?: number; // Acquisition ou Location Client (optionnel)
    mensCli?: number; // Mensualités Client (optionnel)
    mtarCli?: number; // Montant Client (optionnel)
    catlogCli?: number; // Catalogue Client (optionnel)
    codContent?: number; // Code Contenu (optionnel)
    codEmp?: string; // Code Employé (optionnel)
    numCpt?: string; // Numéro de Compte (optionnel)
    comCli?: string; // Commentaire Client (optionnel)
    respCli?: string; // Responsable Client (optionnel)
    situationCli?: string; // Situation Client (optionnel)
    classClient?: string; // Classe Client (optionnel)
    anneeBudgCli?: string; // Année Budgétaire Client (optionnel)
    etat?: string; // État (optionnel)
    codGrp?: string; // Code Groupe (optionnel)
    rang?: string; // Rang (optionnel)
    ordre?: number; // Ordre (optionnel)
    ancienCode?: string; // Ancien Code (optionnel)
    datMaj?: string; // Date de Mise à Jour en format ISO 8601 (optionnel)
    traiter?: string; // Traiter (optionnel)
    codTier?: string; // Code Tiers (optionnel, répété dans l'entité)
    numCompte?: string; // Numéro de Compte (optionnel)
}

